name: deploy-on-vercel
description: Deploy on Vercel

inputs:
  environment:
    description: 'Environment'
    required: true
  gleam_version:
    description: 'Gleam version'
    required: true
  vercel_org_id:
    description: 'Vercel org ID'
    required: true
  vercel_project_id:
    description: 'Vercel project ID'
    required: true
  vercel_token:
    description: 'Vercel token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Vercel CLI
      shell: bash
      run: npm install --global vercel@latest
    - name: Pull Vercel Environment Information
      shell: bash
      env:
        VERCEL_ORG_ID: ${{ inputs.vercel_org_id }}
        VERCEL_PROJECT_ID: ${{ inputs.vercel_project_id }}
      run: vercel pull --yes --environment=${{ inputs.environment }} --token=${{ inputs.vercel_token }}
    - name: Set up Gleam
      uses: erlef/setup-beam@v1
      with:
        otp-version: "27.0"
        gleam-version: ${{ inputs.gleam_version }}
        rebar3-version: "3"
    - name: Build app
      shell: bash
      run: |
        cd src/server/client
        gleam deps download
        gleam run -m lustre/dev add tailwind
        sed -i 's|pub const public = False|pub const public = True|' src/ghx/constants.gleam
        gleam run -m lustre/dev build app --minify
    - name: Copy output to dist
      shell: bash
      run: |
        mkdir -p dist
        cp src/server/client/index.html dist
        cp -r src/server/client/priv dist
        rm dist/priv/static/ghx.css
        rm dist/priv/static/ghx.mjs
        sed -i 's|priv/static/ghx.mjs|priv/static/ghx.min.mjs|' dist/index.html
        sed -i 's|priv/static/ghx.css|priv/static/ghx.min.css|' dist/index.html
    - name: Deploy Project Artifacts to Vercel
      shell: bash
      env:
        VERCEL_ORG_ID: ${{ inputs.vercel_org_id }}
        VERCEL_PROJECT_ID: ${{ inputs.vercel_project_id }}
      run: vercel deploy --target=${{ inputs.environment }} dist --token=${{ inputs.vercel_token }} --yes
