name = "ghx"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_json = ">= 3.0.2 and < 4.0.0"
gleam_stdlib = ">= 0.62.1 and < 1.0.0"
lustre = ">= 5.3.2 and < 6.0.0"
lustre_http = ">= 1.0.0 and < 2.0.0"
plinth = ">= 0.7.2 and < 1.0.0"
gleam_time = ">= 1.4.0 and < 2.0.0"

[dev-dependencies]
lustre_dev_tools = ">= 1.9.2 and < 2.0.0"
